---
title: "Applying to the Marine Ecological Theory Lab"
---

As an advisor, I seek to promote scientific rigor, self-confidence and collegiality in my lab. I will support your ability to conduct independent research and help you thrive as independent researchers. Ultimately, I aim to foster a respectful atmosphere in my lab by having transparent expectations of me as a mentor and my students as mentees.
  
<div style="text-align: left">  
<span style="font-size:1.5em;"> Prospective Graduate Students </span>

I accept MS and PhD students through the <a href="https://mbiograd.manoa.hawaii.edu/"> Marine Biology Graduate Program</a>. The Marine Ecological Theory Lab mght be a good fit for you if: <br>

1. You are interested in ecological modeling as your primary research approach. This means that an MS student thesis will likely comprise an entirely theoretical thesis (i.e., mathematical analyses and computer simulations) while a PhD thesis may be entirely theoretical or contain one or two empirical chapters. I am highly supportive of my students pursuing a combination of lab- and/or field-work with modeling, but know that I will only be able to directly train you in the latter. As such, any empirical work you want to do will most likely be an independent pursuit on your end (e.g., raising funds, developing collaborations, and obtaining permits). <br><br> I am particularly interested in students that have a <b>biology</b> undergraduate degree with a strong quantitative background (at least 1 semester of Calculus, and ideally classes such as differential equations and linear algebra) and those with a <b>mathematics/physics/computer science</b> degree with an interest in ecological marine systems.

2. You are broadly interested in working on marine systems and/or climate change impacts on populations. We have active projects addressing questions on coral reefs, oysters and Hawaiian social-ecological systems. I am excited about both basic and applied research questions, as well as general and system-specific ecological and evolutionary questions.

3. You are team-oriented and excited to contribute your passion, ideas and skills to the lab and to the broader communities at HIMB and UH-Manoa.


If you are interested in applying to the Marine Ecological Theory Lab, please contact me (mcmanusl(at)hawaii.edu) with a description of your research interests, your research background, why you want to work in our lab, and a CV (including GPA). 

Currently, I am only accepting graduate students that come with their own funding such as the <a href = "https://www.nsfgrfp.org/">NSF GRFP</a>, <a href = "https://ndseg.sysplus.com/">NDSEG</a>, <a href = "https://fosterscholars.noaa.gov/">NOAA Nancy Foster</a> and <a href = "https://seagrant.noaa.gov/NMFS-SG-Fellowship">NOAA/SG Population Dynamics</a>. For candidates that are a very good fit for the lab, I would be happy to discuss and help you prepare fellowship applications. I suggest getting in touch by early Fall the year before you would like to start graduate school. <br><br>


<span style="font-size:1.5em;"> Prospective Undergraduate Students </span>

I am always happy to discuss potential research projects for undergraduate students. Please see the 'Prospective Graduate Students' section to see if you would be a good fit for the lab. For current undergraduates at UH Manoa, we can apply for funding together (including for a stipend) through the <a href="https://manoa.hawaii.edu/undergrad/urop/student-funding/project/about/"> Undergraduate Research Opportunities Program</a>. If you are interested in joinining the Marine Ecological Theory Lab, please contact me (mcmanusl(at)hawaii.edu) with a description of your educational background (major, relevant coursework), research interests, and why you want to work in our lab. <br><br>


<span style="font-size:1.5em;"> Prospective Postdoctoral Researchers </span>

I am actively looking for postdocs so please get in touch if you think our research interests align. I am happy to assist in developing fellowship applications to funding opportunities such as <a href="https://beta.nsf.gov/funding/opportunities/postdoctoral-research-fellowships-biology-prfb">NSF Biology</a>, <a href="https://beta.nsf.gov/funding/opportunities/ocean-sciences-postdoctoral-research-fellowships-oce-prf-0">NSF Oceanography</a>, <a href="https://cpaess.ucar.edu/cgc/annual-recruitment-announcement">NOAA Climate & Global Change Postdoctoral Program</a>, <a href="http://www.smithfellows.org/">David H. Smith Conservation Research Fellowship</a> and the <a href="https://lsrf.org/">Life Sciences Research Foundation</a>. <br><br>


</div>
