---
title: "Teaching"
---
<div style="text-align: left">  
<span style="font-size:1.5em;"> MBIO 740 - Mathematical Ecology of Marine Systems</span>
 (Official course number pending)
<br>
I plan to teach this 3-week intesive course annually beginning Fall 2021.
<br>

**Schedule:** This is an intensive, 12-session course with a hybrid (i.e., partially in-person and partially online) schedule. 
<br>

**Description:** This course will cover the use of mathematical approaches to gain a deeper understanding of ecological dynamics. Students will be introduced to a broad range of theories and techniques from mathematical ecology with an emphasis on marine systems. Topics will include single-species populations, community ecology, spatial patterns and population genetics. Students will learn to interpret equations and figures in the theoretical ecology literature, develop critical thinking skills with regards to model assumptions and level of detail, construct their own simple models, and apply analytical and computational techniques to make predictions regarding system behavior. This course will be centered on 'pen and paper' mathematical analyses, coding activities and collaborative group work. There will be a programming component that will introduce computational approaches to simulate dynamical systems using Python. Students will be encouraged to use data collected from their own research or from other courses in their final modeling projects.
<br>

**Syllabus:** Forthcoming.

</div>
